name: Sync with Organization Repository

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add organization repository as remote
        run: git remote add upstream https://github.com/MAHA-Software-Engineering/NHTSA-Frontend.git

      - name: Set Git identity
        run: |
          git config --global user.email "hooghirm29@gmail.com"
          git config --global user.name "hooghir"  

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge --allow-unrelated-histories upstream/main      

      - name: Push changes to fork
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.nhtsa_fork }}
      
