name: Sync with Organization Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: git fetch https://github.com/MAHA-Software-Engineering/NHTSA-Frontend.git

      - name: Merge upstream changes
        run: git merge https://github.com/MAHA-Software-Engineering/NHTSA-Frontend.git/main

      - name: Push changes to fork
        run: |
          git push origin HEAD:main