name: Sync with Organization Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge upstream changes
        run: |
          git fetch upstream
          git merge --ff-only upstream/main || echo "No new changes to merge"

      - name: Push changes to fork
        run: |
          git push origin HEAD:main