name: Sync with Organization Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add organization repository as remote
        run: git remote add upstream https://github.com/MAHA-Software-Engineering/NHTSA-Frontend.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge --allow-unrelated-histories upstream/main      

      - name: Push changes to fork
        run: |
          git push origin HEAD:main
